version: "3.7"
services:
  web:
    image: nginx:1.15.5-alpine
    ports:
      - "80:80"
    volumes:
      - ../app/config/nginx.conf:/etc/nginx/conf.d/app.conf:ro
    networks:
      - frontend
  app:
    build:
      context: ../app
      dockerfile: ../devops/dockerfiles/app-runner/Dockerfile
    networks:
      - frontend
      - backend
  db:
    image: postgres:10.5-alpine
    volumes:
      - database:/var/lib/postgresql
      - ../app/src/ansible/roles/web/files/initial_data.sql:/docker-entrypoint-initdb.d/initital_data.sql:ro
    env_file:
      - ../app/config/.env
    networks:
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  database: ~
