# Generated by Django 2.1.2 on 2018-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation_paid_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
