# Generated by Django 2.1.2 on 2018-11-03 17:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('pages', '0023_auto_20180619_1705'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('membership', '0004_auto_20181103_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRegistrationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('thankyou_page_title', models.CharField(help_text="Title text to use for the 'thank you' page", max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='membershipformfield',
            name='page',
        ),
        migrations.RemoveField(
            model_name='membershippage',
            name='feed_image',
        ),
        migrations.RemoveField(
            model_name='membershippage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='MembershipFormField',
        ),
        migrations.DeleteModel(
            name='MembershipPage',
        ),
    ]
