# Generated by Django 2.1.2 on 2018-11-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_membershipregistrationpage_thank_you_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='membership',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
    ]
