# Generated by Django 2.1.2 on 2018-11-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_auto_20181103_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('R', 'Regular'), ('Se', 'Senior'), ('St', 'Student'), ('L', 'Legacy'), ('C', 'Complimentary')], default='R', max_length=25),
        ),
    ]
