# Generated by Django 2.1.2 on 2018-11-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20181103_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('I', 'Individual'), ('SE', 'Senior'), ('St', 'Student'), ('L', 'Legacy'), ('C', 'Complimentary')], default='I', max_length=25),
        ),
    ]
