# Generated by Django 2.1.2 on 2018-11-03 23:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('pages', '0032_auto_20181103_2114'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('membership', '0009_auto_20181103_2128'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MembershipRegistrationPage',
            new_name='MembershipApplicationPage',
        ),
    ]
