# Generated by Django 2.1.2 on 2018-11-04 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_auto_20181104_0227'),
        ('membership', '0010_auto_20181104_0233'),
    ]

    operations = [
    ]
