# Generated by Django 2.1.2 on 2018-12-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0019_auto_20181104_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='newsletter',
            new_name='digital_newsletter',
        ),
        migrations.AddField(
            model_name='membership',
            name='print_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
