# Generated by Django 2.1.3 on 2018-11-03 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('member_type', models.CharField(choices=[('R', 'Regular'), ('S', 'Student'), ('L', 'Lifetime'), ('C', 'Complimentary')], default='R', max_length=25)),
                ('agency', models.CharField(blank=True, max_length=124, null=True)),
                ('address1', models.CharField(max_length=124)),
                ('address2', models.CharField(blank=True, max_length=124, null=True)),
                ('zip_code', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=124)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('work_telephone', models.CharField(blank=True, max_length=25, null=True)),
                ('newsletter_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('billing_quarter', models.CharField(blank=True, max_length=25, null=True)),
                ('dues_paid', models.DateField(blank=True, null=True)),
                ('newsletter', models.BooleanField(default=False)),
                ('create_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
