# Generated by Django 2.1.2 on 2018-11-03 19:09

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20181103_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipregistrationpage',
            name='thank_you_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Text for the user to see on registration confirmation'),
        ),
    ]
