# Generated by Django 2.1.2 on 2018-11-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_auto_20181103_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
