# Generated by Django 2.1.2 on 2018-11-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_membership_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_type',
            field=models.CharField(choices=[('I', 'Individual'), ('Se', 'Senior'), ('St', 'Student'), ('L', 'Legacy'), ('C', 'Complimentary'), ('B', 'Baxter')], default='I', max_length=25),
        ),
    ]
