# Generated by Django 2.1.2 on 2018-11-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_auto_20181104_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
