# Generated by Django 2.1.2 on 2018-11-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0016_membership_amount'),
        ('membership', '0015_auto_20181104_0318'),
    ]

    operations = [
    ]
