# Generated by Django 2.1.2 on 2018-11-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='paid_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
