# Generated by Django 2.1.2 on 2018-11-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryindex_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryindex',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
    ]
