# Generated by Django 2.1.2 on 2018-11-03 18:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_awardpage_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awardpage',
            name='year',
        ),
        migrations.AddField(
            model_name='awardpage',
            name='date_awarded',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 18, 9, 36, 492295, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
