# Generated by Django 2.1.2 on 2018-11-03 20:25

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20181103_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
