# Generated by Django 2.1.2 on 2018-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_standardindexpage_sidebar_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardindexpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_index_page.html', 'Default Template'), ('pages/standard_index_page_grid.html', 'Grid Also In This Section')], default='pages/standard_page.html', max_length=255),
        ),
    ]
