# Generated by Django 2.1.2 on 2018-11-04 02:37

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20181104_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='sidebar_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='standardindexpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_index_page.html', 'Standard page with sibling pages in sidebar'), ('pages/standard_index_page_grid.html', 'Standard page with sibling pages at bottom'), ('pages/standard_page.html', 'Standard Page, customized sidebar optional')], default='pages/standard_page.html', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_page.html', 'Default Template, optional sidebar'), ('pages/standard_page_full.html', 'Standard Page Full')], default='pages/standard_page.html', max_length=255),
        ),
    ]
