# Generated by Django 2.1.2 on 2018-11-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('pages', '0038_auto_20181104_1318'),
    ]

    
