# Generated by Django 2.1.2 on 2018-11-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20181104_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
    ]
