# Generated by Django 2.1.2 on 2018-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20181103_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
