# Generated by Django 2.1.2 on 2018-11-04 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_paypalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalsettings',
            name='donation_button_id',
            field=models.CharField(default='', help_text='Enter the donation payment button ID', max_length=255),
        ),
        migrations.AddField(
            model_name='paypalsettings',
            name='membership_button_id',
            field=models.CharField(default='', help_text='Enter the membership payment button ID', max_length=255),
        ),
        migrations.AddField(
            model_name='paypalsettings',
            name='url',
            field=models.CharField(default='www.sandbox.paypal.com', help_text='Enter the Paypal URL', max_length=255),
        ),
    ]
