# Generated by Django 2.1.2 on 2018-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181104_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalsettings',
            name='donation_button_id',
        ),
        migrations.RemoveField(
            model_name='paypalsettings',
            name='membership_button_id',
        ),
        migrations.AddField(
            model_name='paypalsettings',
            name='email',
            field=models.CharField(default='', help_text='Enter your Paypal email address', max_length=255),
        ),
    ]
