# Generated by Django 2.1.2 on 2018-11-04 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('pages', '0033_storefrontpage'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('products', '0011_storefrontpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storefrontpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='StoreFrontPage',
        ),
    ]
