# Generated by Django 2.1.2 on 2018-11-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20181104_0233'),
        ('products', '0012_auto_20181104_0251'),
    ]

    operations = [
    ]
