# Generated by Django 2.1.2 on 2018-11-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_merge_20181104_1423'),
        ('products', '0012_auto_20181104_1451'),
    ]

    operations = [
    ]
