# Generated by Django 2.1.2 on 2018-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_merge_20181104_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
