# Generated by Django 2.1.2 on 2018-12-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20181104_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snipcartsettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='SnipcartSettings',
        ),
    ]
