# Generated by Django 2.1.2 on 2018-12-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20181208_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpage',
            name='inventory',
            field=models.IntegerField(default=0, help_text='Current inventory on hand. Items with 0 or blank will not be available for purchase.'),
        ),
        migrations.AddField(
            model_name='productpage',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping cost', max_digits=6),
        ),
    ]
