# Generated by Django 2.1.2 on 2018-12-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20181208_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='inventory',
            field=models.IntegerField(default=1, help_text='Current inventory on hand. Items with 0 or blank will not be available for purchase.'),
        ),
        migrations.AlterField(
            model_name='productpage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
