# Generated by Django 2.1.2 on 2018-12-08 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_auto_20181208_1305'),
        ('products', '0019_auto_20181208_1301'),
    ]

    operations = [
    ]
