# Generated by Django 2.1.2 on 2018-12-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_merge_20181208_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpage',
            name='member_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
