# Generated by Django 2.1.2 on 2018-11-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_awardpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardpage',
            name='winner',
            field=models.CharField(default='Thomas R. Diley', max_length=255),
            preserve_default=False,
        ),
    ]
