# Generated by Django 2.1.2 on 2018-11-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20181103_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
