# Generated by Django 2.1.2 on 2018-11-04 01:56

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20181103_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardindexpage',
            name='sidebar_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
