# Generated by Django 2.1.2 on 2018-11-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20181104_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardindexpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_index_page.html', 'Default Template'), ('pages/standard_index_page_grid.html', 'Standard page with sibling pages at bottom'), ('pages/standard_page.html', 'Standard Page')], default='pages/standard_page.html', max_length=255),
        ),
    ]
