# Generated by Django 2.1.2 on 2018-11-04 03:18

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0021_image_file_hash'),
        ('pages', '0037_auto_20181104_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='pagebreak_image',
            field=models.ForeignKey(blank=True, help_text='If this image exists for this page, there will be a page break 100 image in the template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='standardindexpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_index_page.html', 'Standard page with sibling pages in sidebar'), ('pages/standard_page_full.html', 'Standard Page, customized sidebar optional')], default='pages/standard_page_full.html', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='sidebar_text',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='only include text/images in here if you want the side bar, otherwise it will render full page'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_page_full.html', 'Default Template, optional custom sidebar'), ('pages/standard_page.html', 'Default Template, newsfeed sidebar')], default='standard_page_full.html', max_length=255),
        ),
    ]
