# Generated by Django 2.1.2 on 2018-11-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20181104_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardindexpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_index_page.html', 'Standard page with sibling pages in sidebar'), ('pages/standard_page_full.html', 'Standard Page, customized sidebar optional')], default='pages/standard_page_full.html', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_page_full.html', 'Default Template, optional custom sidebar'), ('pages/standard_page.html', 'Default Template, newsfeed sidebar')], default='standard_page_full.html', max_length=255),
        ),
    ]
