# Generated by Django 2.1.2 on 2018-11-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20181104_0240'),
        ('pages', '0033_storefrontpage'),
    ]

    operations = [
    ]
