# Generated by Django 2.1.2 on 2018-11-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_auto_20181104_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpage',
            name='pagebreak_image',
        ),
        migrations.AddField(
            model_name='standardpage',
            name='midpage_subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
