# Generated by Django 2.1.2 on 2018-11-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20181104_1348'),
        ('pages', '0038_merge_20181104_1423'),
    ]

    operations = [
    ]
