# Generated by Django 2.1.2 on 2018-11-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_merge_20181104_1528'),
        ('pages', '0039_auto_20181104_1324'),
    ]

    operations = [
    ]
