# Generated by Django 2.1.2 on 2018-11-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_merge_20181104_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardindexpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='awardpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='faqspage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='storefrontpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='testimonialpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='videogallerypage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='standardindexpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_index_page.html', 'Child pages in sidebar'), ('pages/standard_page_full.html', 'Customized sidebar optional')], default='pages/standard_page_full.html', help_text='Which layout for this page?', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='template_string',
            field=models.CharField(choices=[('pages/standard_page_full.html', 'Optional custom sidebar'), ('pages/standard_page.html', 'Newsfeed sidebar')], default='pages/standard_page_full.html', help_text='Which layout for this page?', max_length=255),
        ),
    ]
