# Generated by Django 2.1.2 on 2018-11-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20181104_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardindexpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='awardpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='faqspage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardindexpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='midpage_subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='storefrontpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonialpage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
        migrations.AlterField(
            model_name='videogallerypage',
            name='subtitle',
            field=models.CharField(blank=True, help_text='This will override the title of the page.', max_length=255),
        ),
    ]
