# Generated by Django 2.1.2 on 2018-11-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20181104_1327'),
        ('pages', '0043_auto_20181104_1400'),
    ]

    operations = [
    ]
